name: Labels
on: push

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      # sync labels
      - uses: crazy-max/ghaction-github-labeler@v5
        if: success()
