name: Publish package
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      # setup node
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      # install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # build
      - name: Build package
        run: yarn run build

      # test
      - name: Run tests
        run: yarn run test

      # publish
      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # generate release notes
      - name: Generate release notes
        if: startsWith(github.ref, 'refs/tags/v')
        id: changelog
        run: |
          npx standard-changelog -i /dev/null -o CHANGES.md

      # create github release
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGES.md
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog.outputs.status == 'unreleased' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: README.md,LICENSE.md
